/*
 *  datepicker.js <%= version %>
 *  https://github.com/Zeumo/datepicker.js
 *
 *  /!\ Don't edit this file directly!
 *  It was generated by the datepicker.js build system.
 */

(function(window) {
  var Picker, pluginName = 'picker';

  <%= contents %>

  window.Picker = Picker;
}(this));
